### ISSUE TITLE
Feature Request: display magic-sealed-data version

### ISSUE THREAD

**Issue by mixmix** [dr4fters/dr4ft#1024]
I love how on the landing page of dr4ft.info it shows clearly the build deployed + mtgjson version.
I think it would also be cool to show which version of  https://github.com/taw/magic-sealed-data the server is currently using.

I also think it's nice because it provides a nod of thanks to @taw who is maintaining that resource :heart:

**Comment by mixmix** [comment]
version could just be the hash of the latest commit, similar to the a[p version

**Comment by tooomm** [comment]
Since we rely on @taw and his booster data now for the best possible (and most realistic) draft/sealed experience, I like the idea to show that on the bottom line of the page!
Linking to his repo, potentially improves participation and the data, too.

It might also help new people to put some information in the README that/how the code automatically pulls/updates data from external sources nowadays (e.g. mtgjson and taw).

**Comment by mixmix** [comment]
<3
This is choice!
