### ISSUE TITLE
problem with dfc's

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#107]
The back sides are not loading.
Experienced this with "Azor's Gateway" and "Journey to Eternity" on draft.info, both from RIX. But also "Legion's Landing" from XLN.

It looks like the back side of the card is treated as a card on their own, I randomly opened the back side of Journey, too:
![front](https://user-images.githubusercontent.com/9874850/37564507-b982e320-2a97-11e8-8de4-f1e44134f7d8.png)
![back](https://user-images.githubusercontent.com/9874850/37564508-ba97fb60-2a97-11e8-9cc0-1de4374c50ed.png)

**Comment by HerveH44** [comment]
Hi, 
Sorry to be late. It seems to be an error of mtgjson explained [here](https://github.com/mtgjson/mtgjson/issues/548). It seems that for several reasons the mtgjson don't update uniformely the data from different sets. So DFC cards from different sets are now impossible to recognize, which is exactly what happens to the new sets... 

So actually I'm hoping that they are going to find a common rule to manage dfc cards soon, because I don't want to set up rules regarding each set in the code, which would create a huge mess...

**Comment by ZeldaZach** [comment]
Checking up on this: MTGJSON has a "names" field to link cards together as the same card object. You can use this with the two entries in AllSets

**Comment by HerveH44** [comment]
@tooomm I am working on a fix:
![peek 2019-02-26 15-27](https://user-images.githubusercontent.com/16805904/53419987-32897100-39db-11e9-8b4f-a9469bdd7fd3.gif)
