### ISSUE TITLE
Bug: Resource Overload

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#1092]
Draft randomly started using 100% cpu and ram for extended periods of time during its re-download phase. It appeared to be dying while trying to download booster data. Draft is offline until we can address this as it killed our servers.

**Comment by ZeldaZach** [comment]
cc: @HerveH44

**Comment by HerveH44** [comment]
Hi @ZeldaZach, sorry but I can't take of dr4ft anymore, as I told you I need to step back from it. I haven't investigated much on your problem but what bugs me is that beta-dr4ft.herokuapp.com is functioning well. So it means that the problem is on your installation. I guess check with "htop" that all the processes of NodeJs linked to dr4ft have been killed (as it could remain some zombie process if you killed the main process to abruptly).

If you can try to run dr4ft from docker, I guess that would enclose it and you could kill it and the child processes very simply.

**Comment by lrawicz** [comment]
@ZeldaZach do you need help with the HerveH44 instructions, or those instructions didn't resolve the issue?

**Comment by ZeldaZach** [comment]
I haven't seen this issue resurrect recently, so I"ll close for now. Can't reproduce rn.
