### ISSUE TITLE
Bug: Players getting kicked out of drafting rooms by other players joining

### ISSUE THREAD

**Issue by HenriLamarre** [dr4fters/dr4ft#1227]
**Webpage**: www.dr4ft.info

Happening over all course of summer. 

## Detailed Description

When players join a room, other players can get kicked out repeatedly

## Further Information

We are playing a commander cube

**Comment by ZeldaZach** [comment]
Any insight on how we can reproduce this?

**Comment by HerveH44** [comment]
One way a player gets kicked out by some other player joining is when they both share the same ID, which only happens when the use the same browser session (eg. two tabs on chrome or firefox). we don't allow the same player to enter 2 times in the same game. If you really want one player to be able to enter the same room, use incognito features on your browser.

**Comment by HerveH44** [comment]
@HenriLamarre do you still have this issue ? If yes, please open another issue and indicate how we can reproduce it. AFAIK it does not seem like a bug but the fact that you can't have multiple tabs in the same browser for the same game.

**Comment by HenriLamarre** [comment]
Hi, I still have this issue, Its not when I have two browsers. It happens when I play with 5 of my friends on different computers. I do not know how to reproduce it, it happens randomly.
Sorry for the inconvenience and thanks for the answers.
