### ISSUE TITLE
Bug: MTGO crashes when importing .dek file outputs

### ISSUE THREAD

**Issue by JhoiraArtificer** [dr4fters/dr4ft#1454]
**Webpage**: 
Files were generated by www.dr4ft.info
**Browser**: 
Variety of browsers used by the drafters

----------------------------------------------------------------------------------

## Background Information

MTGO (updated as of 10 February 2021) experiences a fatal error and crashes when importing .dek output of dr4ft.info events

Draft options were:
* Cube draft
* 3 packs with 15 cards from a pool of 540 cards
* Picks per pack: 1

## Detailed Description

Today (10 February 2021, most recent update), I was acting as the draft "secretary" and importing decklists to trade people cube cards. We have always used the .txt output files before without too much trouble, but this time people sent me .dek outputs from the online draft. When I attempt to import the .dek files to MTGO using the "Add deck" icon in the lower left corner of the window in the Collection view, MTGO experiences a fatal error and crashes. I have attached a .txt file of the full error reporting to this bug.

MTGO also errors when I attempt to import the decklist .dek as a binder using the icon in the lower left corner of the window. The only information provided is a pop-up reading "An error was encountered when reading the file". MTGO doesn't crash.

## Further Information

[MTGO dek import as deck error.txt](https://github.com/dr4fters/dr4ft/files/5963141/MTGO.dek.import.as.deck.error.txt)

All the drafters had already closed the draft event, but on the off-chance the URL can provide you useful information, it is https://dr4ft.info/#g/9f9fff90-6c18-11eb-bbd5-1149a9be737e .

**Comment by mixmix** [comment]
Thanks for the bug report.
Can you please attach a broken dek file, or open it in a text editor and copy the contents in here?

**Comment by LotusWalker** [comment]
Dr4ft Version: e20371a

Saw this bug and decided to run a test, and I had exactly the same issue (a crash) when importing the DEK file into MTGO, as either a deck or a binder.

**Comment by LotusWalker** [comment]
I couldn't attach the broken DEK file from my draft because Github doesn't seem to support it, but here's the contents:

<?xml version="1.0" encoding="UTF-8"?>
<Deck xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NetDeckID>0</NetDeckID>
  <PreconstructedDeckID>0</PreconstructedDeckID>

  <Cards CatID="60897" Quantity="1" Sideboard="false" Name="Daze" Annotation="0" />
  <Cards CatID="80461" Quantity="1" Sideboard="false" Name="Lurrus of the Dream-Den" Annotation="0" />
  <Cards CatID="35737" Quantity="1" Sideboard="false" Name="Stoneforge Mystic" Annotation="0" />
  <Cards CatID="54863" Quantity="1" Sideboard="false" Name="Grave Titan" Annotation="0" />
  <Cards CatID="43921" Quantity="1" Sideboard="false" Name="Craterhoof Behemoth" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Mox Pearl" Annotation="0" />
  <Cards CatID="60731" Quantity="1" Sideboard="false" Name="Dack Fayden" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Ancestral Recall" Annotation="0" />
  <Cards CatID="70007" Quantity="1" Sideboard="false" Name="Bitterblossom" Annotation="0" />
  <Cards CatID="70187" Quantity="1" Sideboard="false" Name="Frantic Search" Annotation="0" />
  <Cards CatID="83297" Quantity="1" Sideboard="false" Name="Shatterskull Smashing" Annotation="0" />
  <Cards CatID="59766" Quantity="1" Sideboard="false" Name="Archangel Avacyn" Annotation="0" />
  <Cards CatID="60843" Quantity="1" Sideboard="false" Name="Nature's Claim" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="High Tide" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Black Lotus" Annotation="0" />
  <Cards CatID="12385" Quantity="1" Sideboard="false" Name="Time Spiral" Annotation="0" />
  <Cards CatID="83421" Quantity="1" Sideboard="false" Name="Turntimber Symbiosis" Annotation="0" />
  <Cards CatID="83023" Quantity="1" Sideboard="false" Name="Skyclave Apparition" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Mana Drain" Annotation="0" />
  <Cards CatID="57088" Quantity="1" Sideboard="false" Name="Tezzeret the Seeker" Annotation="0" />
  <Cards CatID="39710" Quantity="1" Sideboard="false" Name="Karn Liberated" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Mox Ruby" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Mishra's Workshop" Annotation="0" />
  <Cards CatID="70527" Quantity="1" Sideboard="false" Name="Fire/Ice" Annotation="0" />
  <Cards CatID="67879" Quantity="1" Sideboard="false" Name="Teferi, Hero of Dominaria" Annotation="0" />
  <Cards CatID="7647" Quantity="1" Sideboard="false" Name="Natural Order" Annotation="0" />
  <Cards CatID="78180" Quantity="1" Sideboard="false" Name="Brazen Borrower" Annotation="0" />
  <Cards CatID="65963" Quantity="1" Sideboard="false" Name="Ancestral Vision" Annotation="0" />
  <Cards CatID="13039" Quantity="1" Sideboard="false" Name="Treachery" Annotation="0" />
  <Cards CatID="79150" Quantity="1" Sideboard="false" Name="Elspeth Conquers Death" Annotation="0" />
  <Cards CatID="57880" Quantity="1" Sideboard="false" Name="Jace, Vryn's Prodigy" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Fiery Confluence" Annotation="0" />
  <Cards CatID="50310" Quantity="1" Sideboard="false" Name="Ashiok, Nightmare Weaver" Annotation="0" />
  <Cards CatID="18932" Quantity="1" Sideboard="false" Name="Brain Freeze" Annotation="0" />
  <Cards CatID="13563" Quantity="1" Sideboard="false" Name="Bribery" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Strip Mine" Annotation="0" />
  <Cards CatID="78538" Quantity="1" Sideboard="false" Name="Oko, Thief of Crowns" Annotation="0" />
  <Cards CatID="78368" Quantity="1" Sideboard="false" Name="Embereth Shieldbreaker" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Chain Lightning" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Demonic Tutor" Annotation="0" />


</Deck>

**Comment by LotusWalker** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Deck xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NetDeckID>0</NetDeckID>
  <PreconstructedDeckID>0</PreconstructedDeckID>

  <Cards CatID="60897" Quantity="1" Sideboard="false" Name="Daze" Annotation="0" />
  <Cards CatID="80461" Quantity="1" Sideboard="false" Name="Lurrus of the Dream-Den" Annotation="0" />
  <Cards CatID="35737" Quantity="1" Sideboard="false" Name="Stoneforge Mystic" Annotation="0" />
  <Cards CatID="54863" Quantity="1" Sideboard="false" Name="Grave Titan" Annotation="0" />
  <Cards CatID="43921" Quantity="1" Sideboard="false" Name="Craterhoof Behemoth" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Mox Pearl" Annotation="0" />
  <Cards CatID="60731" Quantity="1" Sideboard="false" Name="Dack Fayden" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Ancestral Recall" Annotation="0" />
  <Cards CatID="70007" Quantity="1" Sideboard="false" Name="Bitterblossom" Annotation="0" />
  <Cards CatID="70187" Quantity="1" Sideboard="false" Name="Frantic Search" Annotation="0" />
  <Cards CatID="83297" Quantity="1" Sideboard="false" Name="Shatterskull Smashing" Annotation="0" />
  <Cards CatID="59766" Quantity="1" Sideboard="false" Name="Archangel Avacyn" Annotation="0" />
  <Cards CatID="60843" Quantity="1" Sideboard="false" Name="Nature's Claim" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="High Tide" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Black Lotus" Annotation="0" />
  <Cards CatID="12385" Quantity="1" Sideboard="false" Name="Time Spiral" Annotation="0" />
  <Cards CatID="83421" Quantity="1" Sideboard="false" Name="Turntimber Symbiosis" Annotation="0" />
  <Cards CatID="83023" Quantity="1" Sideboard="false" Name="Skyclave Apparition" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Mana Drain" Annotation="0" />
  <Cards CatID="57088" Quantity="1" Sideboard="false" Name="Tezzeret the Seeker" Annotation="0" />
  <Cards CatID="39710" Quantity="1" Sideboard="false" Name="Karn Liberated" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Mox Ruby" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Mishra's Workshop" Annotation="0" />
  <Cards CatID="70527" Quantity="1" Sideboard="false" Name="Fire/Ice" Annotation="0" />
  <Cards CatID="67879" Quantity="1" Sideboard="false" Name="Teferi, Hero of Dominaria" Annotation="0" />
  <Cards CatID="7647" Quantity="1" Sideboard="false" Name="Natural Order" Annotation="0" />
  <Cards CatID="78180" Quantity="1" Sideboard="false" Name="Brazen Borrower" Annotation="0" />
  <Cards CatID="65963" Quantity="1" Sideboard="false" Name="Ancestral Vision" Annotation="0" />
  <Cards CatID="13039" Quantity="1" Sideboard="false" Name="Treachery" Annotation="0" />
  <Cards CatID="79150" Quantity="1" Sideboard="false" Name="Elspeth Conquers Death" Annotation="0" />
  <Cards CatID="57880" Quantity="1" Sideboard="false" Name="Jace, Vryn's Prodigy" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Fiery Confluence" Annotation="0" />
  <Cards CatID="50310" Quantity="1" Sideboard="false" Name="Ashiok, Nightmare Weaver" Annotation="0" />
  <Cards CatID="18932" Quantity="1" Sideboard="false" Name="Brain Freeze" Annotation="0" />
  <Cards CatID="13563" Quantity="1" Sideboard="false" Name="Bribery" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Strip Mine" Annotation="0" />
  <Cards CatID="78538" Quantity="1" Sideboard="false" Name="Oko, Thief of Crowns" Annotation="0" />
  <Cards CatID="78368" Quantity="1" Sideboard="false" Name="Embereth Shieldbreaker" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Chain Lightning" Annotation="0" />
  <Cards Quantity="1" Sideboard="false" Name="Demonic Tutor" Annotation="0" />


</Deck>

**Comment by LotusWalker** [comment]
Hmmm when I paste it in it looks fine, but then doesn't copy over when I hit send.

**Comment by LotusWalker** [comment]
Just emailed it to you @mixmix

**Comment by mixmix** [comment]
You have to put it in a " code block" (I edited your post, click edit again to see how I did it - triple backticks ```)

**Comment by mixmix** [comment]
Yeah I'm sorry nothing obvious stands out. In absence of a spec for their dek format we're guessing?

If someone is up for it I would try "bisection method" :
- take that file and cut out half the cards, as if that fixes it
- keep cutting out more and more cards till it works
- replace cards back until you find the broken one

You might need to make a line for say 40 mountains to make sure there's at least 40 cards there?

Lmk if you need more help

**Comment by JhoiraArtificer** [comment]
Sure, I'd be happy to help with this (I did save one of the bad .dek files but completely forgot to try attaching it... I'm sorry!). I don't have time to work on this until at least 5pm PST but will do if nobody else has stepped up by then.

**Comment by LotusWalker** [comment]
I'll give this a try as well. Will let you know how it goes.

**Comment by LotusWalker** [comment]
ok, found the problem. I started by trimming the DEK file down to just 5 cards, all of which had a CatID. That file could be imported into MTGO without a problem. Then I added a 6th card, which didn't have a CatID, and tried to import it. MTGO then crashed just as @JhoiraArtificer previously reported. So it seems that, unfortunately, MTGO does require all cards to have a CatID.

**Comment by nex3** [comment]
Note that MTGO does accept decks in a very simply `.txt` format—exporting that format may be simpler than trying to match the undocumented `.dek` format.

**Comment by mixmix** [comment]
But @LotusWalker, we previously tested not including catId with ancestral recall didn't we?

What was the name of the falling card?

**Comment by mixmix** [comment]
@nex3 good point, you might be quite right.
We can always export as `.mtgo.txt` to do people know what the deck is formatted for!

**Comment by LotusWalker** [comment]
@mixmix Yeah you’re right, but I must have made a mistake when we tested last time, perhaps by not saving the DEK file after editing it..? Not sure. MTGO also just released a new version 1-2 days ago, so maybe that was a factor.

Mox Pearl was the failing card, but I just tested it again with Ancestral Recall being the only card without a CatID, and it caused a crash for that card as well. So I think we can be confident that the lack of CatID is the culprit here.

I have no preference between TXT or DEK for MTGO file downloads. But it is important that they’re formatted in the proper way so they can be successfully imported into MTGO.

**Comment by mixmix** [comment]
TXT would be a lot easier than this.

If we did want the DEK format, I have found a way to do it - basically the problem is when dr4ft imports the cube (from the text field anyway), it resolves the card by looking up as a flow `name -> different options -> chosen option`. The "chosen option" is determined by a few things but it will default back to some particular card. In the case of Mox Pearl, it's 2ED version, and this one does not have an mtgoId.....   Looking at the other options there are versions which DO have mtgoId.

I think I'm leaning towards not adding all this logic to drf4ft, as it will result in showing people (perhaps) card versions they didn't want in their draft .... Maybe if MTGO has good importing / parsing logic on it's side, then we should just lean on that?!

**Comment by mixmix** [comment]
For fun: 

versions of Mox Pearl found by dr4ft:

```
{
  default: 'd7c371a4-bc40-5bd8-a486-220584bf4b84',
  '2ed': { '264': 'd7c371a4-bc40-5bd8-a486-220584bf4b84' },
  lea: { '263': 'bdbc1b80-5371-5af3-9c7c-6ec166c2cf5c' },  <<<< has mtgoId
  leb: { '264': 'd43a8822-4241-5a60-897b-f141247a9fb6' },
  ced: { '264': '3ea68549-a2e2-5331-a47c-f993694a5880' },
  cei: { '264': 'bdd4c5e6-84c4-5c19-9e22-360e1af86e15' },
  ovnt: {
    '2006': '4c2622de-2c4f-55f6-aa7c-318e34a5e0a8',
    '2014': 'b15f5762-868f-5165-b484-8bc152535fc8',
    '2019': '84b91a7d-38a6-5b21-a4ea-0e4a34e37f29'
  },
  prm: { '46892': '3df76f36-430b-5b56-ac69-31fabe72f4b0' },  <<<< has mtgoId
  vma: { '7': '1057945e-66e0-5cc4-a9ed-44748a6526a7' }  <<<< has mtgoId
}
```

**Comment by mixmix** [comment]
Ok, can someone show me a "happy" txt format file which will import for MTGO?
guess:

```
Deck
1 Card A
4 Card B

Sideboard
2 Card C
```

**Comment by LotusWalker** [comment]
Yeah probably best/easiest then to just get rid of the DEK download option for MTGO and replace it with TXT downloads, but ensuring that they are in the correct format to be accepted for import into MTGO.

**Comment by LotusWalker** [comment]
Sure, gimme a few mins I’ll try to make one which includes all the variety of cards someone could want to import (adventure, split, transform, mdfc, etc.)

**Comment by LotusWalker** [comment]
@mixmix Just emailed you a sample that works in MTGO.

**Comment by mixmix** [comment]
Can you show me what it looks like when some of those are in the sideboard?

**Comment by JhoiraArtificer** [comment]
> Yeah probably best/easiest then to just get rid of the DEK download option for MTGO and replace it with TXT downloads, but ensuring that they are in the correct format to be accepted for import into MTGO.

That would be great... the only meaningful problem I've run into with importing TXT files is format disagreement in split cards, DFCs, etc. If that's ironed out, there's really not a huge advantage (at least in our use case) for a DEK over a TXT.

**Comment by LotusWalker** [comment]
Totally agree @JhoiraArtificer 

@mixmix MTGO is often weird with the sideboards. Like for example if I put 5 cards from a draft in the sideboard sometimes when I import all the cards are there, but a different number ends up in the sideboard, etc. So I basically never use the sideboard option in Dr4ft because it doesnt really convert well into mtgo...I just build the deck and sideboard within mtgo itself.

**Comment by mixmix** [comment]
Hmm. I would still like to try and support sideboard. If mtgo has bugs there's a chance it will work in future....

So is it like I suggested above?

```
3 a card
4 more card

Sideboard
2 some card
```

**Comment by LotusWalker** [comment]
@mixmix Yes exactly.
