### ISSUE TITLE
use mtgjson allset data + xml/json extensions as card input

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#37]
Instead only one allset.json data file.
Right now you have to combine and include all spoilers into the mtgjson data and create a new file with all data mixed.

I think it would be way better and cleaner to manage if we handle the mtgjson allset file and and any additional data (spoilers, other games, custom sets, ...) as separate files.
Allows to easily update without changing all data and recreating of a new big all-in-on file, smaller files in general, better overview, no merge of unrelated or approved/unconfirmed cards etc.pp.

**Comment by HerveH44** [comment]
Hi @tooomm , 

How do you imagine updating the "cards.json" ? When we would add a new XXX.json file (spoilers of next season for example) then we would launch "npm run updateCardsDB" or something like this to update the "cards.js" ? 

But how do you clean the cards.js from all the previous sets or spoilers unwanted? It seems a bit hard? 

@dev-id it would be crazy to imagine using a real DB ? I don't know like a mysql or mongo?

**Comment by HerveH44** [comment]
Hi, 

I'm currently working on adding a MongoDB database to the project. Doing so, I plan to simplify creation and addition of new or custom sets. There will be few commands to integrate a set to the current database. 
I try to figure out if I shouldkeep the structurae of sets.json and cards.json, in terms of "document" which are tightly linked with the business logic. I was thinking of simple documents for sets with only "ID" and "Name" and then have a simplified version of mtgjson cards in another table. The problem is that the way we create the pools of cards for sealed and drafts (what I called the Business Logic) would have to be modified as well... 
So right now, I'm thinking that I should go to the simplest way and reproduce the structure of sets.json and cards.json into the database, and keep the same BL. And maybe later change the whole structure to be simpler. 

Hervé

**Comment by ZeldaZach** [comment]
Shouldn't be a problem anymore, as we've using v4 that includes spoilers
