### ISSUE TITLE
Host Option - Force Hidden Draft

### ISSUE THREAD

**Issue by ZeldaZach** [dr4fters/dr4ft#392]
With the new feature of #45 added, we should have an option for a host to "force" this mode onto players. To make this work as expected, we'll also need to add a timer in between packs so players can view their cards and move things around from main and side.

**Comment by HerveH44** [comment]
I have some thoughts about this issue. I wanted to do it this weekend, but after a bit I got convinced that we shouldn't do it. 
Neither MTGO nor MTGArena have introduced this kind of behaviour, I feel that's for a good reason. Maybe it's because you can't control that your opponent is not cheating this rule (like doing print screen of picks/packs or just writing the picks on paper), maybe it's for another reason but I think that's unless a good part of our players want to introduce it, we shouldn't develop something new that would add some complexity on the code for no reason. 

So I'd close the issue and leave the app with the possibility for an individual to hide his picks to himself if he wants to, as it's been developed.

**Comment by tooomm** [comment]
Some people play with friends where trust is not that much of an issue, or they simply don't care.
Others want to do it just for themselves to practice and simulate a real paper draft for preparation reasons.

>possibility for an individual to hide his picks to himself 

I've no idea how one should properly simulate hiding his picks...

**Comment by ZeldaZach** [comment]
Yeah I can see Herve's point. This is moot, and we give them the option to hide if they so desire.
