### ISSUE TITLE
setup Heroku Review Apps

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#66]
It's a pretty fancy and useful tool to check changes within PR's live!
We should be all good with just the free plan, and it seamlessly integrates with GitHub.

Announcement in blog: https://blog.heroku.com/heroku-review-apps-ga
Documentation: https://devcenter.heroku.com/articles/github-integration-review-apps

Other (hopefully helpful) links:
https://github.com/infusionsoft/heroku-review-app-guide
http://blog.skorfmann.com/heroku-review-apps
https://robots.thoughtbot.com/running-acceptance-with-review-apps

@HerveH44 you had some concerns or additional requirements that would need to change before we could use it. Can you let us know here again, please?

---
**Note: https://zeit.co/now could be an interesting alternative**

**Comment by HerveH44** [comment]
Hey, 

From my point of vue, right now our app runs through a Make command, and not directly through NodeJs. I think we need to focus on putting all the make commands inside NodeJs package.json as scripts and then have the app runs through simple "npm start", because that's a requisite from Heroku Apps.

For example, all the links created, the big AllSets JSON download, should be done through new scripts, and put an entry inside package.json like "postinstall". Because that's what Heroku is going to trigger after he does "npm install". 

I'll put some more information soon, when I am finished with the refactoring. 

Bye ! 

Hervé

**Comment by HerveH44** [comment]
Just for information, 

it's super simple to set review apps, and it works fine. I just tried it with my branch refactor_frontend.

@dev-id Would you like to create an account on Heroku ?

**Comment by tooomm** [comment]
Not useful yet. But first bits got merged, want to outline that here for reference: https://github.com/dr4fters/dr4ft/pull/29/commits/42da6573fab681db76c3c003547192002d1f55bd

**Comment by HerveH44** [comment]
Fixed with commit : 031f8343b18d229a879f8dd6d9f44c8b1bf6d1b9
