### ISSUE TITLE
Auto hide chat if game is started with only one player

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#688]
If a player is the only person in a game room and still starts, he doesn't need the chat as there is nobody else he could talk with. :)

I for myself do sometimes pool building practise for sealed. Alone.
First thing I do after I started the game is to hide the chat - every single time I open a new pool. It just takes up valuable space and is of no use for single player rooms imo.

**Comment by HerveH44** [comment]
That's not so easy. 

Would it be better if we would just save the state of the chat window? Since the creation of the chat component we don't save the state. But since messages are shown as "toasts" when the chat is closed, I think it could be simpler to just remember the state of the chat window. So if you close it during a game, your next game will have it closed to (and reciprocally)

**Comment by tooomm** [comment]
You are right, it’s not saved currently!That would also help and the toasts make you not miss chats.

If checking for the human player count is not so easy.

**Comment by ZeldaZach** [comment]
I'm a fan of saving chat open/closed state to cookies
