### ISSUE TITLE
New mtgjson version pattern breakes link to changelog

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#692]
Homepage reads:
![dr4ft](https://user-images.githubusercontent.com/9874850/69495599-0bf45a00-0ec9-11ea-8bdc-120df27c17a9.png)

Clicking the mtgjson version used to correctly link to the changelog on the mtgjson site.
Link is: https://mtgjson.com/changelog/#_4-6-0+20191122-2019-11-22
Should be: https://mtgjson.com/changelog/#_4-6-0-2019-10-28

The new daily builds and their date appended to the semver most likely breakes the correct jump right into the corresponding changelog.

**Comment by HerveH44** [comment]
The problem is that the version in [mtgjson.com/files/version.json](https://mtgjson.com/files/version.json) doesn't correspond to the actual changelog version. The version found is always appended with the build metadata (things that follow a plus sign) which doesn't exist in the changelogs. 

@ZeldaZach the build metadata (mostly the date of the build) isn't important right? I mean the semver rules say that "Build metadata MUST be ignored when determining version precedence" so at the moment dr4ft don't refresh the sets if only the last build metadata have changed. Is that correct?

**Comment by ZeldaZach** [comment]
Weekly builds only address issues found in the content (so it theoretically could be called a PATCH), but it can be safely ignored for the most part.

**Comment by tooomm** [comment]
There are weekly builds?

I only knew about the proper releases (code changes only?) and the daily new price builds.

**Comment by HerveH44** [comment]
actually the changelog is made with also the date which is not right at the moment (last build at the moment of v4.6.0 is 2019-11-24 but the changelog indicates the date 2019-10-28).

@ZeldaZach could it be possible for you to either not show the date in the changelog (or at leat now in the tag to pin the changelog -> for example https://mtgjson.com/changelog/#_4-6-0 should be enough and not https://mtgjson.com/changelog/#_4-6-0-2019-10-28)

**Comment by tooomm** [comment]
>actually the changelog is made with also the date which is not right at the moment (last build at the moment of v4.6.0 is 2019-11-24 but the changelog indicates the date 2019-10-28).

The changelog indicates the release of 4.6.0 version which was at 28th of october. That's correct.
Since then only daily price updates are run, that's why 4.6.0 stays the same and the date of price updates is appended. At least that's how I understood it.
I don't know what happens with those weekly builds zach mentioned and if other data get updated as well in the daily (and weekly?) updates?!

Striping the date from the link on the webpage doesn't harm I guess. It can still be displayed there, but should not be part of the link 👍 
Linking/pinning to the correct changelog location would be easier.
