### ISSUE TITLE
Mystery Booster not showing..

### ISSUE THREAD

**Issue by Flutschi** [dr4fters/dr4ft#891]
Hey there, dont know if you know but i guess mystery booster was a bit too big to show?

Would be a blast if we could draft mystery in these times..

**Comment by aSipiere** [comment]
I've created a paired down file from the MB1 and CMB1 files on mtgjson, by adding the cards together and removing a few of the more wordy keys from each card, this gets it down to 1.7MB which is small enough for uploading a custom set.

But I'm getting a `"the json submitted is not valid: Cannot read property 'type' of undefined"`.

This was the python script I used to generate it if you wanna have a go.

```python
import json

with open("./MB1CMB1.json", encoding="utf8") as file:
    mb1cmb1 = json.load(file)
    
bad_keys = [
    'edhrecRank',
    'foreignData',
    'legalities',
    'prices',
    'purchaseUrls',
    'tcgplayerProductId',
    'rulings'
]

for card in mb1cmb1['cards']:
    for k in bad_keys:
        card.pop(k, None)
        
with open('mb1cb1-small.json', 'w') as outfile:
    json.dump(mb1cmb1, outfile)
```

I created the file by splicing together the cards list from MB1 and CMB1 and changing the the total set size. I have a feeling that dr4ft is dependant on one of the fields I've killed. But it would be nice not to have to do it through trial and error.

**Comment by aSipiere** [comment]
Upon further investigation, the doset method seems to be complaining about the set not having a type tag when the file has `'type': 'funny'`.

**Comment by aSipiere** [comment]
Creating a new issue for this to tidy up.

**Comment by ZeldaZach** [comment]
cc: @HerveH44

**Comment by aSipiere** [comment]
Mystery booster is a particularly weird one since its MB1 and (FMB1 or CMB1), additionally mtgjson doesn't have a booster order for it.

2 white commons or uncommons
2 blue commons or uncommons
2 black commons or uncommons
2 red commons or uncommons
2 green commons or uncommons
1 multicolor common or uncommon
1 artifact or land common or uncommon
1 rare or mythic rare from before Core Set 2015
1 other rare or mythic rare
1 foil card / playtest card

Which makes sense since it's such a weird one compared to other draft innovations sets.

**Comment by aSipiere** [comment]
@Flutschi as a temporary measure you should be able to see `Myster Booster Convention Edition` in the custom set's list, however that version doesn't have the above booster pack structure, but it does have all the cards (with playtest cards instead of retail foils).
