### ISSUE TITLE
Feature Request: Rich Man's Draft

### ISSUE THREAD

**Issue by resech** [dr4fters/dr4ft#919]
It'd be great to be able to run a Rich Man's Draft (I've also seen it referred to as Decadent Sealed) through the app. 

For anyone who isn't familiar with it, each player starts with a booster box/36 packs then:

- Opens a pack
- Selects a single card
- Discards the rest of the pack
- Opens another pack and repeats

Once all the packs have been opened, you build a deck from your 36 card pool.

**Comment by ZeldaZach** [comment]
We'd be open to a pull request if  you'd like to contribute!

**Comment by keeler** [comment]
I'd like to give this a shot. Would appreciate some pointers from @ZeldaZach, @HerveH44, or anyone else. Willing to try figuring this out on my own but a rough idea of where to start would probably save time/effort for us all when I submit a PR. :grin:

**Comment by HerveH44** [comment]
I will make a review soon, I'm thinking of a video or something as I guess it would take some time to explain everything in a comment. There are multiple things to consider but I guess the biggest would be how to pass packs between picks as it's kind of an in-between sealed and draft (sealed because players just have there own packs and none are passed, and draft because you still pick one card from a pack). There's also a minor issue on frontend (how to present a mode which is draft only?). 

If I have time this week I'll make something. If anybody knows where I could host it, that would be fine.

**Comment by ZeldaZach** [comment]
If you're looking to make a video, you can make an unlisted YouTube video, or just put the MP4 on Dropbox
