### ISSUE TITLE
Drafting custom cube set

### ISSUE THREAD

**Issue by troman-hub** [dr4fters/dr4ft#965]
Hello, 
we tried to upload our custom cube set to draft it online and then play on Cockatrice. Unfortunately, we could not see the card images as well as the cards' stats.

Magic set editor exports P/T stats in the following way: <pt>3/1</pt>
Is it the right way?

Thanks in advance – we noticed you live in Udine just like me and my playgroup!

**Comment by ZeldaZach** [comment]
Hi @troman-hub can you paste your custom set on this ticket?

**Comment by IlMath** [comment]
[DomeCube.zip](https://github.com/dr4fters/dr4ft/files/4471582/DomeCube.zip)

Cards are in Italian, but the fields are the one exported directly from MSE

**Comment by ZeldaZach** [comment]
The reason you can't see images on dr4ft is because you did not include an `picURL` attribute. Per the [Cockatrice Wiki](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets), a set tag should look like `<set rarity="common" uuid="12345678-abcd-1234-abcd-1234567890ab" num="42" muid="123456" picurl="http://.../image.jpg">XXX</set>` where you define the set code (replacing XXX) and define alternative stats for the image loaders. Not all of them appear to be requried, but picurl is the one you're probably going to want to set.

I hope this helps point you in the right direction!

**Comment by IlMath** [comment]
Thank you so much,
I manage to upload all the images, but there is one more problem.
After I open my Cube with the card list, the images are still missing, but
if I open a draft with three packs (the set is the Dome Cube in Custom,
that I just find out is public :O ), images are working fine (unless the
ones that we have problems with. The cube is still an ongoing project)

Do you have any advise why is working in one way and not in the other?

Thank you in advance,
Best Regards,
__________________
Mattia Pellegrini Miani


Il giorno lun 13 apr 2020 alle ore 22:04 Zach H <notifications@github.com>
ha scritto:
