### ISSUE TITLE
Feature Request: "Grab a Bag" Draft/Sealed

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#999]
"Grab a Bag" Draft and Sealed options, where every player chooses a pack (set) for all group, are currently not possible.
Would require to change sets from within an already created room.

I don't necessarily suggest that every player can select a set.
But people can make a decision in the game room chat for example and the host adjusts the options accordingly without the need to recreate the room.

**Comment by HerveH44** [comment]
I'm doubtful about the real utility of this one... I feel that it would be a big work to do for something that I feel is doable now (create a game, ask for people to make their choice and then recreate a new game with the correct sets). 

I need more support from the players to know if it's a big deal for them, otherwise I would not want to implement it (or put it to a very low priority).

**Comment by ZeldaZach** [comment]
I'm on Herve's side here. This feels overkill and doesn't add much value to the service.
